### ISSUE TITLE
Adding an exception fails

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-exception-pages#5]
Trying to edit this exception: https://docs.typo3.org/typo3cms/exceptions/master/en-us/Exceptions/1427455378.html I get an error

```Most likely the exception you are trying to access is not a valid TYPO3 Core exception but rather caused by a 3rd-party extension.```

Even though the exception was thrown in /var/www/html/web/typo3/sysext/frontend/Classes/ContentObject/ContentDataProcessor.php

should be available as this exception code is at least in the basic https://github.com/TYPO3-Documentation/t3docs-exception-pages/blob/master/app/packages/exception-pages/res/exceptions/exceptions.php#L1414
someone would have to check in the server log what is causing the error

**Comment by susannemoog** [comment]
@alexander-nitsche the PUT request for creating the page for 1427455378 results in a HTTP 409 response from github. You should be able to reproduce that by manually trying that request. Can you take a look at how that case should be handled?

**Comment by alexander-nitsche** [comment]
When sending the request locally i get this error message in the GitHub API response:
```
{"message":"Could not create file: Required status check \"use-docker-container (online)\" is expected. At least 1 approving review is required by reviewers with write access.","documentation_url":"https:\/\/docs.github.com\/articles\/about-protected-branches"}{"message":"Could not create file: Required status check \"use-docker-container (online)\" is expected. At least 1 approving review is required by reviewers with write access.","documentation_url":"https:\/\/docs.github.com\/articles\/about-protected-branches"}
```
This is the same error message as shown in the current two PRs of this repository which show a yellow status, which means that continuous integration tasks have not finished yet - since approximatly 20 days!

The problems i can imagine are
1. The git clone URL `git://git.typo3.org/Packages/TYPO3` is not supported anymore and was still used in this project.
2. Some repository access restrictions have been set lately which require at least 1 review for every commit, and this coincides with creating a new file on-the-fly in the master branch.

I will fix (1) in the branch `task-fix-creating-new-exception-page`, someone else could check the access restrictions.

**Comment by alexander-nitsche** [comment]
Fixing (1) did not solve the issue. So it is probably due to the access restrictions (2).

**Comment by alexander-nitsche** [comment]
Updating the branch protection rules solved the issue:

1. I removed the typo3-documentation-team user from the list of users which have to create a PR first before merging.
2. I disabled the "Require status checks to pass before merging"
